spring.application.name=obs-backend

# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/obsdb
spring.datasource.username=obsuser
spring.datasource.password=obspass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Run data.sql after JPA schema creation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server
server.port=8080
